version: '3'

volumes:
  users_database_data:
  products_database_data:

services:

  api:
    build:
      context: rest_api/
    ports:
      - "8000:80"
    env_file:
      - .env
    command: "uvicorn --host 0.0.0.0 --port 80 app.main:app --reload"
    volumes:
      - "./rest_api:/app"
    depends_on:
      - users_srv
      - products_srv

  users_srv:
    build:
      context: users_service/
    volumes:
    - "./users_service:/app"
    env_file:
      - .env

  products_srv:
    build:
      context: products_service/
    volumes:
      - "./products_service:/app"
    env_file:
      - .env