# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discounter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="discounter.proto",
    package="discount",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x10\x64iscounter.proto\x12\x08\x64iscount\x1a\x0emessages.proto2I\n\nDiscounter\x12;\n\x12\x63\x61lculate_discount\x12\x10.DiscountRequest\x1a\x11.DiscountResponse"\x00\x62\x06proto3',
    dependencies=[
        messages__pb2.DESCRIPTOR,
    ],
)


_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_DISCOUNTER = _descriptor.ServiceDescriptor(
    name="Discounter",
    full_name="discount.Discounter",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=46,
    serialized_end=119,
    methods=[
        _descriptor.MethodDescriptor(
            name="calculate_discount",
            full_name="discount.Discounter.calculate_discount",
            index=0,
            containing_service=None,
            input_type=messages__pb2._DISCOUNTREQUEST,
            output_type=messages__pb2._DISCOUNTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_DISCOUNTER)

DESCRIPTOR.services_by_name["Discounter"] = _DISCOUNTER

# @@protoc_insertion_point(module_scope)
