# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="products.proto",
    package="products",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0eproducts.proto\x12\x08products\x1a\x0emessages.proto2\x81\x01\n\x08Products\x12\x38\n\x0bget_product\x12\x12.GetProductRequest\x1a\x13.GetProductResponse"\x00\x12;\n\x0cget_products\x12\x13.GetProductsRequest\x1a\x14.GetProductsResponse"\x00\x62\x06proto3',
    dependencies=[
        messages__pb2.DESCRIPTOR,
    ],
)


_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_PRODUCTS = _descriptor.ServiceDescriptor(
    name="Products",
    full_name="products.Products",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=45,
    serialized_end=174,
    methods=[
        _descriptor.MethodDescriptor(
            name="get_product",
            full_name="products.Products.get_product",
            index=0,
            containing_service=None,
            input_type=messages__pb2._GETPRODUCTREQUEST,
            output_type=messages__pb2._GETPRODUCTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_products",
            full_name="products.Products.get_products",
            index=1,
            containing_service=None,
            input_type=messages__pb2._GETPRODUCTSREQUEST,
            output_type=messages__pb2._GETPRODUCTSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_PRODUCTS)

DESCRIPTOR.services_by_name["Products"] = _PRODUCTS

# @@protoc_insertion_point(module_scope)
